### ISSUE TITLE
Duplicate test?

### ISSUE THREAD

**Issue by cdenneen** [jfryman/puppet-selinux#102]
@jfryman Can I ask what this line is for exactly?

https://github.com/jfryman/puppet-selinux/blob/master/spec/classes/selinux_package_spec.rb#L32
30 seems to do similar test.. so I'm trying to figure out the context it's run in.

**Comment by jfryman** [comment]
@cdenneen Nope, no reason. I think this was a merge gone wrong. Thanks!
