### ISSUE TITLE
no tag for 0.2.5

### ISSUE THREAD

**Issue by pizzaops** [jfryman/puppet-selinux#51]
Lots of users use r10k with git rather than the forge, which is more difficult without release tags. Might you be willing to add a tag for the latest forge release, 0.2.5?

Thanks!

**Comment by ncsujjpryor** [comment]
I second pizzaops comment. We too use this module with r10k.
Thanks.

**Comment by jfryman** [comment]
Appreciate you using the module!

I've pushed updated tag `0.2.5`. Will stay on top of that for future releases too. Sorry about the oversight

**Comment by pizzaops** [comment]
Thank you!
