### ISSUE TITLE
why is disabled the default mode?

### ISSUE THREAD

**Issue by nbeernink** [jfryman/puppet-selinux#68]
I fail to understand why this module by default disables SELinux. Can an explanation perhaps be added to the documentation?

**Comment by thrnio** [comment]
This PR actually got merged a half hour before you posted to change just that :)

https://github.com/jfryman/puppet-selinux/pull/67

**Comment by nbeernink** [comment]
Thanks, I saw the PR but didn't realise the default would also be fixed. Thanks for the headsup. :)
