### ISSUE TITLE
Release to Puppet Forge?

### ISSUE THREAD

**Issue by bklang** [jfryman/puppet-selinux#7]
We are using your SELinux module as a dependency for our new [https://forge.puppetlabs.com/mojolingo/openshift](OpenShift module).  As such, would you consider making a release of this module available on [Puppet Forge](http://forge.puppetlabs.com) so other users can resolve dependencies automatically?  I'm happy to help do the packaging if desired.

**Comment by jfryman** [comment]
All done. https://forge.puppetlabs.com/jfryman/selinux/readme
