### ISSUE TITLE
selinux_custom_policy.rb:8: syntax error, unexpected ':', expecting kEND

### ISSUE THREAD

**Issue by sharkannon** [jfryman/puppet-selinux#76]
`selinux_custom_policy.rb:8: syntax error, unexpected ':', expecting kEND
  confine kernel: 'Linux', osfamily: 'RedHat', ...
                 ^

selinux_custom_policy.rb:8: syntax error, unexpected ',', expecting kEND
  confine kernel: 'Linux', osfamily: 'RedHat', operating...
                          ^

selinux_custom_policy.rb:8: syntax error, unexpected ',', expecting kEND
...: 'Linux', osfamily: 'RedHat', operatingsystemmajrelease: '7...
                              ^

selinux_custom_policy.rb:8: syntax error, unexpected ',', expecting kEND
...peratingsystemmajrelease: '7', selinux: ['true', true]
                              ^`

We get this when running this on:
OS: Centos 6.6
Ruby: 1.8.7
Facter 2.4.4
Puppet: 3.7.5
puppet-selinux: 0.3.0

I did some quick checks and it appears that the confine syntax may be wrong (at least for our version of ruby etc).. looking at the puppet docs it should be something like

`confine :kernel => 'Linux'`

**Comment by Thubo** [comment]
I can confirm that issue, running on

```
OS: Centos 6.7
Ruby: 1.8.7
Facter 2.4.4
Puppet: 3.8.4
puppet-selinux: 0.3.0
```

**Comment by jkroepke** [comment]
Hi!

This issue has been fixed by the pr. It this possible to publish 0.3.1 to forge?

**Comment by Rican7** [comment]
Yea, seems like this has been fixed. A `0.3.1` release would be helpful. :smiley:
