### ISSUE TITLE
Fedora 23 package name changed

### ISSUE THREAD

**Issue by logic** [jfryman/puppet-selinux#82]
In Fedora 23, after the switch to python3, `policycoreutils-python` has generally been renamed to `policycoreutils-python3`. Also, most of the utilities (including the `semanage` command) have moved to `policycoreutils-python-utils`, which is probably the better package name to target.

(Yes, they're named inconsistently. I have no good explanation, this is just what it is. :wink: )

**Comment by jfryman** [comment]
Ugh. Lame.

Think you could throw together a PR?

**Comment by ncsutmf** [comment]
Looks like Fedora 21 and up also require policycoreutils-devel to get the /usr/share/selinux/devel/Makefile, which has policycoreutils-python-utils as a requirement.  Working on updating my pull request #89 to take that into account and that should also resolve this issue.
