### ISSUE TITLE
Missing package selinux-policy-devel

### ISSUE THREAD

**Issue by gauthier-delacroix** [jfryman/puppet-selinux#84]
When upgrading to 0.3.0 from 0.2.3 on my CentOS 7.2 server, I had this error: 

    Failed to call refresh: make -f /usr/share/selinux/devel/Makefile local_mypol.pp returned 2 instead of one of [0]

The `/usr/share/selinux/devel/Makefile` directory is created by package `selinux-policy-devel` which is not installed on my server. The module seems to require it so maybe it should be added as a dependancy ?

**Comment by jfryman** [comment]
Would you please open up a PR? Happy to review/merge

**Comment by ncsutmf** [comment]
Just noticed I had submitted a similar issue and later submitted a fix.  See Issue #88 and Pull Request #89 

Fix in the Pull Request is to change the package name for Redhat/CentOS 7 from policycoreutils-python to policycoreutils-devel.  RPM dependencies get selinux-policy-devel and policycoreutils-python installed in this case.
