### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mmerfort** [jfryman/puppet-selinux#85]
It would be great to get a new release of the module. I prefer to use forge modules whenever possible and the current release still contains #80 which makes it unusable.

**Comment by EslamElHusseiny** [comment]
+1

**Comment by fculpo** [comment]
:+1:

**Comment by s34gull** [comment]
+1

**Comment by mikalsande** [comment]
+1

**Comment by jfryman** [comment]
Of course. Thanks for your patience, and double :heart: for using this module! :bow:

I have quite literally been in the middle of some major life changes (including a job change, and some other personal matters), but things are settling now. As part of this change, I'll have a bit more time to keep on top of my OSS projects.

A new version has been released to the forge (v0.3.1). Enjoy!
