### ISSUE TITLE
Problems with package duplicate declaration (ensure_packages?)

### ISSUE THREAD

**Issue by toddnni** [jfryman/puppet-selinux#87]
I bumbed in to an issue that another selinux module provides **policycoreutils-python** by using **ensure_packages()** function. However, as this module is not using the function, in some cases **ensure_packages()** version is fired first and manifests/package.pp:24 will emit an error about the duplicate declaration.

I was able to work around the problem by defining **selinux::manage_package: false**, but should we also use **ensure_packages()** in this module to fix the issue without workaround?

**Comment by jfryman** [comment]
@toddnni if you provide a PR, more than happy to review and merge. I don't particularly care that this module has responsibility for those package resources, so `ensure_resource` would be a good substitution.
