### ISSUE TITLE
selinux-module failing on RHEL 7, Makefile not there

### ISSUE THREAD

**Issue by ncsutmf** [jfryman/puppet-selinux#88]
Regarding a [comment from Pull Request #73](https://github.com/jfryman/puppet-selinux/pull/73#issuecomment-156832199)

It appears RedHat decided to split selinux into the selinux-policy and selinux-policy-devel packages for RHEL 7, and put /usr/share/selinux/devel/Makefile in the devel package.  I assume this would also affect CentOS 7 and recent versions of Fedora as well.

The .te file gets created but no .mod or .pp file in /usr/share/selinux.

I didn't notice it until recently because the .mod and .pp files were already there, but I think the addition of the prefix caused it to attempt to install the module under a new name and then start giving puppet errors.

RHEL 6 seams to have the Makefile in selinux-policy and as best I can tell there is no selinux-policy-devel for RHEL 6.

Thoughts on the best way to fix this?

**Comment by legooolas** [comment]
I'd suggest that either:
 - The "package_name" param should be changed to allow a list of packages, which includes selinux-policy-devel on RHEL7-based distros
 - A separate "module_package_name" param is added and used to include the package only when the selinux::module definition is used.

I'm happy to provide a patch for whichever of these is preferable (or something else :) as I'm adding the package explicitly for now and it would be nice to have the selinux module handle this on my behalf.

**Comment by ncsutmf** [comment]
Currently the package is policycoreutils-python which causes selinux-policy to install as well.  I have already submitted a pull request #89 to change it to policycoreutils-devel, which requires policycoreutils-python and also causes selinux-policy-devel to install.

**Comment by legooolas** [comment]
Fab -- I'll clobber this as that will fix the problem.  Also gives a handy workaround of overriding the package_name to be `policycoreutils-python-devel` for now  :)

**Comment by ncsutmf** [comment]
policycoreutils-devel (no 'python' on the name)
