### ISSUE TITLE
custom te file loads every time  RE: Only allow refresh in the event that the initial .te file is updated.

### ISSUE THREAD

**Issue by shollingsworth** [jfryman/puppet-selinux#95]
Hello,

I have the below code block in one of my classes and every time I run puppet agent it displays the following message:

`Notice: /Stage[main]/my_ldap_auth::Selinux_ssh_homedir/Selinux::Module[selinux_ssh_homedir]/Selmodule[local_selinux_ssh_homedir]/ensure: created`

Caller
```
   selinux::module { 'selinux_ssh_homedir':
     source => 'puppet:///modules/modpath/selinux_ssh_homedir.te',
     require => Package['policycoreutils-devel'],
   }
```

Here are some standard variables from facter.

`os => {"name"=>"CentOS", "family"=>"RedHat", "release"=>{"major"=>"7", "minor"=>"2", "full"=>"7.2.1511"}} `

```
# facter  |grep selinux
selinux => true
selinux_config_mode => enforcing
selinux_config_policy => targeted
selinux_current_mode => enforcing
selinux_enforced => true
selinux_policyversion => 28
````

Any help would be appreciated.

Thanks!

**Comment by Fabian1976** [comment]
Several people have come accross this issue. See:
https://github.com/jfryman/puppet-selinux/pull/92
https://github.com/jfryman/puppet-selinux/issues/90

A fix has been proposed by someone, but it is nog yet merged and versioned.

I find it strange that the most popular selinux module is so buggy. Don't know if it is still maintained by jfryman

**Comment by jfryman** [comment]
> the most popular selinux module

WOW! I had no idea. Thanks for the nice words.

I could always have another maintainer helping me out like I do with some of my other popular modules. I had no idea this one had traction, to be completely honest. Up for the job?

Otherwise, I hope everyone understands this is free work. I'll continue to do my best. Thanks for the bug reports and code!
